name: example
description: A new Flutter project.











version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  
  
  feature_discovery:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  pedantic: any





flutter:

  
  
  
  uses-material-design: true
